export const types = {
    CLARO:'CLARO',
    OSCURO:'OSCURO',
    LECTURA:'LECTURA',
    LOGGIN: 'LOGGIN',
    LOGOUT: 'LOGOUT',
    BIG_FONT: 'BIG_FONT',
    MEDIUM_FONT: 'MEDIUM_FONT',
    TINNY_FONT: 'TINNY_FONT',
    NOTIFICATION_ON:'NOTIFICATION_ON',
    NOTIFICATION_OFF:'NOTIFICATION_OFF'    
}